//! `afwe init` – scaffold an empty `.afwe/` (as empty as the codebase it starts with)
//! and `afwe bootstrap` – propose an initial blueprint for an existing codebase.

use crate::engine::Engine;
use crate::model::*;
use crate::store::Store;
use crate::util::slug;
use anyhow::{anyhow, Result};
use std::collections::BTreeMap;
use std::path::Path;

pub const AFWE_README: &str = r#"# .afwe/ — Architecture-First Workspace Engine

This folder is a persistent, multi-level, two-way model of this codebase. It sits between
an LLM harness and the IDE. Humans and models both read it; the `afwe` engine keeps it in
sync with the code and tells you when they disagree.

| path | what it is | who writes it |
| --- | --- | --- |
| `afwe.yaml` | manifest, analyzer settings, confidence policy | humans / `afwe init` |
| `blueprint/blueprint.yaml` | the deterministic architecture tree + implementation mapping (files, symbols) | humans, LLMs, `afwe sync` (confident reconciliations only) |
| `blueprint/relations.yaml` | declared and inferred relationships between nodes | humans, LLMs, `afwe sync` |
| `blueprint/constraints.yaml` | structural rules that `afwe verify` enforces | humans, LLMs |
| `memory/<kind>/*.md` | knowledge: decisions, constraints, exceptions, terminology, problems — with scope metadata | humans, LLMs |
| `guardrails/passive/*.yaml` | micro-context injected when work touches their scope | humans, LLMs |
| `guardrails/active/*.yaml` | checks (commands, forbidden imports/patterns) that turn intent into errors | humans, LLMs |
| `workflows/*.yaml` | node-based workflows: intent → design → implementation, with provenance | humans, LLMs, studio |
| `abstractions/*.yaml` | custom lenses: a different grouping of the same nodes | humans, studio |
| `contracts/*.yaml` | what the harness must do when work crosses an AFWE boundary | humans |
| `index/` | derived retrieval index (regenerated by `afwe sync`) | engine |
| `state/` | derived: drift report, proposals, board, sync state | engine |
| `log/changes.jsonl` | append-only history of what changed, by whom, with confidence | engine |

Memory files = source of knowledge. Index = source of location. Code = source of implementation.
"#;

pub struct InitOptions {
    pub name: Option<String>,
    pub description: Option<String>,
    pub root: Option<String>,
    pub force: bool,
}

pub fn init(project_root: &Path, opts: InitOptions) -> Result<Store> {
    let store = Store::new(project_root);
    if store.exists() && !opts.force {
        return Err(anyhow!(".afwe/ already exists at {} (use --force to reset the manifest)", store.afwe_dir.display()));
    }
    let name = opts.name.unwrap_or_else(|| project_root.canonicalize().ok().and_then(|p| p.file_name().map(|s| s.to_string_lossy().to_string())).unwrap_or("project".into()));
    let manifest = Manifest { format: FORMAT_VERSION.into(), project: ProjectMeta { name: name.clone(), description: opts.description, root: opts.root.unwrap_or(".".into()) }, analyzer: AnalyzerConfig::default(), policy: Policy::default(), provenance: ProvenanceConfig::default() };
    store.save_manifest(&manifest)?;
    if !store.p("blueprint/blueprint.yaml").exists() {
        let root = BlueprintNode { id: slug(&name), name: name.clone(), kind: "product".into(), purpose: Some("Root of the architecture. Everything the project is lives beneath this node.".into()), description: None, implements: Implementation::default(), tags: vec![], status: Some("active".into()), origin: Some("human".into()), children: vec![] };
        store.save_blueprint(&Blueprint { nodes: vec![root] })?;
    }
    if !store.p("blueprint/relations.yaml").exists() {
        store.save_relations(&Relations::default())?;
    }
    if !store.p("blueprint/constraints.yaml").exists() {
        store.save_constraints(&Constraints::default())?;
    }
    for k in MEMORY_KINDS {
        std::fs::create_dir_all(store.p(&format!("memory/{k}")))?;
        let keep = store.p(&format!("memory/{k}/.gitkeep"));
        if !keep.exists() {
            std::fs::write(keep, "")?;
        }
    }
    for d in ["guardrails/passive", "guardrails/active", "workflows", "abstractions", "index", "state", "log"] {
        std::fs::create_dir_all(store.p(d))?;
    }
    if store.contracts()?.is_empty() {
        for c in crate::contract::default_contracts() {
            store.save_contract(&c)?;
        }
    }
    store.write_text("README.md", AFWE_README)?;
    store.write_text(".gitignore", "# derived state is reproducible; keep the sources of truth in git\nindex/code.json\n")?;
    let engine = Engine { store: store.clone() };
    engine.log("human", "init", format!("Initialised .afwe for `{name}`"), None)?;
    Ok(store)
}

/// Propose an initial blueprint from the directory structure of an existing codebase.
/// Top-level source directories become subsystems, their immediate children modules.
/// Everything is marked `origin: afwe:bootstrap` so humans/LLMs know it is a guess.
pub fn bootstrap(engine: &Engine, depth: usize, apply: bool) -> Result<Blueprint> {
    let manifest = engine.store.manifest()?;
    let code = engine.analyzer(&manifest).analyze()?;
    let mut bp = engine.store.blueprint()?;
    let root_id = bp.nodes.first().map(|n| n.id.clone()).unwrap_or_else(|| slug(&manifest.project.name));
    if bp.nodes.is_empty() {
        bp.nodes.push(BlueprintNode { id: root_id.clone(), name: manifest.project.name.clone(), kind: "product".into(), purpose: None, description: None, implements: Implementation::default(), tags: vec![], status: Some("active".into()), origin: Some("human".into()), children: vec![] });
    }
    // count code files per directory prefix
    let mut dirs: BTreeMap<String, usize> = BTreeMap::new();
    for f in &code.files {
        if matches!(f.language.as_str(), "other" | "json" | "yaml" | "toml" | "markdown") {
            continue;
        }
        let parts: Vec<&str> = f.path.split('/').collect();
        for d in 1..parts.len().min(depth + 1) {
            *dirs.entry(parts[..d].join("/")).or_default() += 1;
        }
    }
    // skip generic wrapper dirs (src, lib, app) by descending into them
    let generic = ["src", "lib", "app", "apps", "packages", "pkg", "internal", "cmd"];
    let mut existing_ids = vec![];
    crate::mapping::all_ids(&bp.nodes, &mut existing_ids);
    fn build(prefix: &str, dirs: &BTreeMap<String, usize>, depth_left: usize, generic: &[&str], ids: &mut Vec<String>) -> Vec<BlueprintNode> {
        let mut out = vec![];
        let children: Vec<(&String, &usize)> = dirs.iter().filter(|(d, _)| {
            let parent = match d.rfind('/') { Some(i) => &d[..i], None => "" };
            parent == prefix
        }).collect();
        for (d, count) in children {
            let name = d.rsplit('/').next().unwrap_or(d).to_string();
            if generic.contains(&name.as_str()) {
                out.extend(build(d, dirs, depth_left, generic, ids));
                continue;
            }
            if *count < 1 || depth_left == 0 {
                continue;
            }
            let id = crate::mapping::unique_id(ids, &name);
            ids.push(id.clone());
            let kids = build(d, dirs, depth_left - 1, generic, ids);
            out.push(BlueprintNode { id, name: humanise(&name), kind: if kids.is_empty() { "module".into() } else { "subsystem".into() }, purpose: None, description: Some(format!("Bootstrapped from `{d}/` ({count} code files). Review and give it a purpose.")), implements: Implementation { files: vec![format!("{d}/**")], symbols: vec![] }, tags: vec!["bootstrapped".into()], status: Some("active".into()), origin: Some("afwe:bootstrap".into()), children: kids });
        }
        out
    }
    let nodes = build("", &dirs, depth, &generic, &mut existing_ids);
    let root = crate::mapping::find_node_mut(&mut bp.nodes, &root_id).unwrap();
    for n in nodes {
        if !root.children.iter().any(|c| c.name == n.name) {
            root.children.push(n);
        }
    }
    if apply {
        engine.store.save_blueprint(&bp)?;
        engine.log("afwe:bootstrap", "bootstrap", format!("Bootstrapped blueprint from directory structure ({} files)", code.files.len()), None)?;
    }
    Ok(bp)
}

fn humanise(s: &str) -> String {
    let mut out = String::new();
    for (i, part) in s.split(|c| c == '-' || c == '_' || c == '.').enumerate() {
        if part.is_empty() {
            continue;
        }
        if i > 0 {
            out.push(' ');
        }
        let mut chars = part.chars();
        if let Some(f) = chars.next() {
            out.push(f.to_ascii_uppercase());
            out.extend(chars);
        }
    }
    out
}
