//! Reading and writing the `.afwe/` folder.
//!
//! Layout (all human readable, git friendly):
//!
//! ```text
//! .afwe/
//! ├── afwe.yaml                  manifest, analyzer settings, confidence policy
//! ├── blueprint/
//! │   ├── blueprint.yaml         deterministic architecture tree + implementation mapping
//! │   ├── relations.yaml         declared / inferred relationships between nodes
//! │   └── constraints.yaml       structural rules (must_not_depend, may_depend_only)
//! ├── memory/{decisions,constraints,exceptions,terminology,problems}/*.md
//! ├── guardrails/{passive,active}/*.yaml
//! ├── workflows/*.yaml           node-based workflows (intent → design → implementation)
//! ├── abstractions/*.yaml        custom lenses
//! ├── contracts/*.yaml           what the harness must do when work crosses an AFWE boundary
//! ├── index/*.json               derived: retrieval / location (regenerated by sync)
//! ├── state/*.json               derived: drift, proposals, board, sync
//! └── log/changes.jsonl          append-only history of what changed and why
//! ```

use crate::model::*;
use anyhow::{anyhow, Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

pub const AFWE_DIR: &str = ".afwe";

#[derive(Debug, Clone)]
pub struct Store {
    /// Directory that contains `.afwe/`.
    pub project_root: PathBuf,
    /// `.afwe/`
    pub afwe_dir: PathBuf,
}

/// Everything that is a *source of truth* in `.afwe/` (not derived state).
#[derive(Debug, Clone, Default)]
pub struct Sources {
    pub manifest: Option<Manifest>,
    pub blueprint: Blueprint,
    pub relations: Relations,
    pub constraints: Constraints,
    pub memory: Vec<MemoryEntry>,
    pub guardrails: Vec<Guardrail>,
    pub workflows: Vec<Workflow>,
    pub lenses: Vec<Lens>,
    pub contracts: Vec<Contract>,
}

impl Store {
    pub fn new(project_root: impl AsRef<Path>) -> Self {
        let project_root = project_root.as_ref().to_path_buf();
        let afwe_dir = project_root.join(AFWE_DIR);
        Self { project_root, afwe_dir }
    }

    /// Walk upwards from `start` to find a directory containing `.afwe/`.
    pub fn discover(start: impl AsRef<Path>) -> Result<Self> {
        let start = start.as_ref().canonicalize().unwrap_or_else(|_| start.as_ref().to_path_buf());
        let mut cur: Option<&Path> = Some(start.as_path());
        while let Some(dir) = cur {
            if dir.join(AFWE_DIR).join("afwe.yaml").is_file() {
                return Ok(Store::new(dir));
            }
            cur = dir.parent();
        }
        Err(anyhow!(
            "no .afwe/ found in {} or its parents (run `afwe init`)",
            start.display()
        ))
    }

    pub fn exists(&self) -> bool {
        self.afwe_dir.join("afwe.yaml").is_file()
    }

    // ── paths ──
    pub fn p(&self, rel: &str) -> PathBuf {
        self.afwe_dir.join(rel)
    }
    pub fn code_root(&self, m: &Manifest) -> PathBuf {
        let r = self.project_root.join(&m.project.root);
        r.canonicalize().unwrap_or(r)
    }

    // ── generic io ──
    pub fn read_yaml<T: serde::de::DeserializeOwned>(&self, rel: &str) -> Result<Option<T>> {
        let path = self.p(rel);
        if !path.is_file() {
            return Ok(None);
        }
        let s = fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
        let v = serde_yaml::from_str(&s).with_context(|| format!("parse {}", path.display()))?;
        Ok(Some(v))
    }
    pub fn write_yaml<T: serde::Serialize>(&self, rel: &str, v: &T) -> Result<()> {
        let path = self.p(rel);
        ensure_parent(&path)?;
        let s = serde_yaml::to_string(v)?;
        fs::write(&path, s).with_context(|| format!("write {}", path.display()))
    }
    pub fn read_json<T: serde::de::DeserializeOwned>(&self, rel: &str) -> Result<Option<T>> {
        let path = self.p(rel);
        if !path.is_file() {
            return Ok(None);
        }
        let s = fs::read_to_string(&path)?;
        Ok(Some(serde_json::from_str(&s).with_context(|| format!("parse {}", path.display()))?))
    }
    pub fn write_json<T: serde::Serialize>(&self, rel: &str, v: &T) -> Result<()> {
        let path = self.p(rel);
        ensure_parent(&path)?;
        fs::write(&path, serde_json::to_string_pretty(v)?)?;
        Ok(())
    }
    pub fn write_text(&self, rel: &str, s: &str) -> Result<()> {
        let path = self.p(rel);
        ensure_parent(&path)?;
        fs::write(&path, s)?;
        Ok(())
    }
    pub fn read_text(&self, rel: &str) -> Result<Option<String>> {
        let path = self.p(rel);
        if !path.is_file() {
            return Ok(None);
        }
        Ok(Some(fs::read_to_string(path)?))
    }
    pub fn remove(&self, rel: &str) -> Result<()> {
        let path = self.p(rel);
        if path.exists() {
            fs::remove_file(path)?;
        }
        Ok(())
    }

    // ── manifest ──
    pub fn manifest(&self) -> Result<Manifest> {
        self.read_yaml::<Manifest>("afwe.yaml")?
            .ok_or_else(|| anyhow!("missing .afwe/afwe.yaml"))
    }
    pub fn save_manifest(&self, m: &Manifest) -> Result<()> {
        self.write_yaml("afwe.yaml", m)
    }

    // ── blueprint ──
    pub fn blueprint(&self) -> Result<Blueprint> {
        Ok(self.read_yaml("blueprint/blueprint.yaml")?.unwrap_or_default())
    }
    pub fn save_blueprint(&self, b: &Blueprint) -> Result<()> {
        self.write_yaml("blueprint/blueprint.yaml", b)
    }
    pub fn relations(&self) -> Result<Relations> {
        Ok(self.read_yaml("blueprint/relations.yaml")?.unwrap_or_default())
    }
    pub fn save_relations(&self, r: &Relations) -> Result<()> {
        self.write_yaml("blueprint/relations.yaml", r)
    }
    pub fn constraints(&self) -> Result<Constraints> {
        Ok(self.read_yaml("blueprint/constraints.yaml")?.unwrap_or_default())
    }
    pub fn save_constraints(&self, c: &Constraints) -> Result<()> {
        self.write_yaml("blueprint/constraints.yaml", c)
    }

    // ── memory (markdown + frontmatter) ──
    pub fn memory(&self) -> Result<Vec<MemoryEntry>> {
        let mut out = vec![];
        for kind_dir in MEMORY_KINDS {
            let dir = self.p(&format!("memory/{kind_dir}"));
            for path in list_files(&dir, "md") {
                let rel = rel_to(&self.afwe_dir, &path);
                match self.read_memory_file(&rel) {
                    Ok(e) => out.push(e),
                    Err(err) => eprintln!("afwe: skipping {}: {err}", rel),
                }
            }
        }
        Ok(out)
    }
    pub fn read_memory_file(&self, rel: &str) -> Result<MemoryEntry> {
        let s = fs::read_to_string(self.p(rel))?;
        let (front, body) = split_frontmatter(&s);
        let mut meta: MemoryMeta = if front.trim().is_empty() {
            MemoryMeta::default()
        } else {
            serde_yaml::from_str(front).with_context(|| format!("frontmatter of {rel}"))?
        };
        let stem = Path::new(rel).file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or_default();
        if meta.id.is_empty() {
            meta.id = stem.clone();
        }
        if meta.kind.is_empty() {
            // memory/decisions/x.md -> decision
            let dir = Path::new(rel).parent().and_then(|p| p.file_name()).map(|s| s.to_string_lossy().to_string()).unwrap_or_default();
            meta.kind = singular(&dir);
        }
        if meta.title.is_empty() {
            meta.title = body
                .lines()
                .find(|l| l.starts_with('#'))
                .map(|l| l.trim_start_matches('#').trim().to_string())
                .unwrap_or(stem);
        }
        Ok(MemoryEntry { meta, body: body.to_string(), path: rel.to_string() })
    }
    pub fn save_memory(&self, e: &MemoryEntry) -> Result<()> {
        let front = serde_yaml::to_string(&e.meta)?;
        let body = e.body.trim_start_matches('\n');
        let s = format!("---\n{front}---\n\n{body}");
        self.write_text(&e.path, &s)
    }
    pub fn memory_path(kind: &str, id: &str) -> String {
        format!("memory/{}/{}.md", plural(kind), id)
    }

    // ── guardrails ──
    pub fn guardrails(&self) -> Result<Vec<Guardrail>> {
        let mut out = vec![];
        for mode in ["passive", "active"] {
            let dir = self.p(&format!("guardrails/{mode}"));
            for path in list_files(&dir, "yaml") {
                let rel = rel_to(&self.afwe_dir, &path);
                let mut g: Guardrail = self.read_yaml(&rel)?.unwrap();
                if g.mode.is_empty() {
                    g.mode = mode.to_string();
                }
                out.push(g);
            }
        }
        Ok(out)
    }
    pub fn save_guardrail(&self, g: &Guardrail) -> Result<()> {
        self.write_yaml(&format!("guardrails/{}/{}.yaml", g.mode, g.id), g)
    }

    // ── workflows ──
    pub fn workflows(&self) -> Result<Vec<Workflow>> {
        let mut out = vec![];
        for path in list_files(&self.p("workflows"), "yaml") {
            let rel = rel_to(&self.afwe_dir, &path);
            if let Some(w) = self.read_yaml::<Workflow>(&rel)? {
                out.push(w);
            }
        }
        Ok(out)
    }
    pub fn workflow(&self, id: &str) -> Result<Workflow> {
        self.read_yaml(&format!("workflows/{id}.yaml"))?
            .ok_or_else(|| anyhow!("workflow `{id}` not found"))
    }
    pub fn save_workflow(&self, w: &Workflow) -> Result<()> {
        self.write_yaml(&format!("workflows/{}.yaml", w.id), w)
    }

    // ── lenses ──
    pub fn lenses(&self) -> Result<Vec<Lens>> {
        let mut out = vec![];
        for path in list_files(&self.p("abstractions"), "yaml") {
            let rel = rel_to(&self.afwe_dir, &path);
            if let Some(l) = self.read_yaml::<Lens>(&rel)? {
                out.push(l);
            }
        }
        Ok(out)
    }
    pub fn save_lens(&self, l: &Lens) -> Result<()> {
        self.write_yaml(&format!("abstractions/{}.yaml", l.id), l)
    }

    // ── contracts ──
    pub fn contracts(&self) -> Result<Vec<Contract>> {
        let mut out = vec![];
        for path in list_files(&self.p("contracts"), "yaml") {
            let rel = rel_to(&self.afwe_dir, &path);
            if let Some(c) = self.read_yaml::<Contract>(&rel)? {
                out.push(c);
            }
        }
        Ok(out)
    }
    pub fn save_contract(&self, c: &Contract) -> Result<()> {
        self.write_yaml(&format!("contracts/{}.yaml", c.id), c)
    }

    // ── derived state ──
    pub fn index(&self) -> Result<Option<Index>> {
        self.read_json("index/index.json")
    }
    pub fn save_index(&self, i: &Index) -> Result<()> {
        // one combined file for the engine + split views for humans/other tools
        self.write_json("index/index.json", i)?;
        self.write_json("index/files.json", &i.files)?;
        self.write_json("index/symbols.json", &i.symbols)?;
        self.write_json("index/memory.json", &i.memory)?;
        self.write_json("index/nodes.json", &i.nodes)?;
        Ok(())
    }
    pub fn code_model(&self) -> Result<Option<CodeModel>> {
        self.read_json("index/code.json")
    }
    pub fn save_code_model(&self, c: &CodeModel) -> Result<()> {
        self.write_json("index/code.json", c)
    }
    pub fn board(&self) -> Result<Board> {
        Ok(self.read_json("state/board.json")?.unwrap_or_default())
    }
    pub fn save_board(&self, b: &Board) -> Result<()> {
        self.write_json("state/board.json", b)
    }
    pub fn proposals(&self) -> Result<Proposals> {
        Ok(self.read_json("state/proposals.json")?.unwrap_or_default())
    }
    pub fn save_proposals(&self, p: &Proposals) -> Result<()> {
        self.write_json("state/proposals.json", p)
    }
    pub fn drift(&self) -> Result<Option<DriftReport>> {
        self.read_json("state/drift.json")
    }
    pub fn save_drift(&self, d: &DriftReport) -> Result<()> {
        self.write_json("state/drift.json", d)
    }
    pub fn sync_state(&self) -> Result<SyncState> {
        Ok(self.read_json("state/sync.json")?.unwrap_or_default())
    }
    pub fn save_sync_state(&self, s: &SyncState) -> Result<()> {
        self.write_json("state/sync.json", s)
    }

    // ── log ──
    pub fn append_log(&self, e: &LogEntry) -> Result<()> {
        let path = self.p("log/changes.jsonl");
        ensure_parent(&path)?;
        use std::io::Write;
        let mut f = fs::OpenOptions::new().create(true).append(true).open(path)?;
        writeln!(f, "{}", serde_json::to_string(e)?)?;
        Ok(())
    }
    pub fn log(&self, tail: usize) -> Result<Vec<LogEntry>> {
        let Some(s) = self.read_text("log/changes.jsonl")? else { return Ok(vec![]) };
        let mut all: Vec<LogEntry> = s.lines().filter_map(|l| serde_json::from_str(l).ok()).collect();
        if tail > 0 && all.len() > tail {
            all = all.split_off(all.len() - tail);
        }
        Ok(all)
    }

    /// Load all sources of truth at once.
    pub fn sources(&self) -> Result<Sources> {
        Ok(Sources {
            manifest: Some(self.manifest()?),
            blueprint: self.blueprint()?,
            relations: self.relations()?,
            constraints: self.constraints()?,
            memory: self.memory()?,
            guardrails: self.guardrails()?,
            workflows: self.workflows()?,
            lenses: self.lenses()?,
            contracts: self.contracts()?,
        })
    }

    /// Fingerprint of all *source* files inside `.afwe/` (not derived state).
    pub fn afwe_fingerprint(&self) -> String {
        let mut hashes: BTreeMap<String, String> = BTreeMap::new();
        for sub in ["afwe.yaml", "blueprint", "memory", "guardrails", "workflows", "abstractions", "contracts"] {
            let p = self.p(sub);
            if p.is_file() {
                if let Ok(b) = fs::read(&p) {
                    hashes.insert(sub.into(), crate::util::hash_bytes(&b));
                }
            } else if p.is_dir() {
                for f in walk_all(&p) {
                    if let Ok(b) = fs::read(&f) {
                        hashes.insert(rel_to(&self.afwe_dir, &f), crate::util::hash_bytes(&b));
                    }
                }
            }
        }
        let joined = hashes.iter().map(|(k, v)| format!("{k}={v}")).collect::<Vec<_>>().join("\n");
        crate::util::hash_str(&joined)
    }
}

// ───────────────────────────── helpers ─────────────────────────────

pub fn ensure_parent(path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    Ok(())
}

pub fn list_files(dir: &Path, ext: &str) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = match fs::read_dir(dir) {
        Ok(rd) => rd
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.is_file() && p.extension().map(|e| e == ext || (ext == "yaml" && e == "yml")).unwrap_or(false))
            .collect(),
        Err(_) => vec![],
    };
    v.sort();
    v
}

pub fn walk_all(dir: &Path) -> Vec<PathBuf> {
    let mut out = vec![];
    if let Ok(rd) = fs::read_dir(dir) {
        let mut entries: Vec<_> = rd.filter_map(|e| e.ok()).map(|e| e.path()).collect();
        entries.sort();
        for p in entries {
            if p.is_dir() {
                out.extend(walk_all(&p));
            } else {
                out.push(p);
            }
        }
    }
    out
}

pub fn rel_to(base: &Path, path: &Path) -> String {
    crate::util::to_unix(path.strip_prefix(base).unwrap_or(path))
}

pub fn split_frontmatter(s: &str) -> (&str, &str) {
    let t = s.trim_start_matches('\u{feff}');
    if let Some(rest) = t.strip_prefix("---") {
        let rest = rest.trim_start_matches(['\r', ' ']).trim_start_matches('\n');
        if let Some(end) = rest.find("\n---") {
            let front = &rest[..end];
            let after = &rest[end + 4..];
            let after = after.trim_start_matches(['\r', ' ']).trim_start_matches('\n');
            return (front, after);
        }
    }
    ("", t)
}

pub fn plural(kind: &str) -> String {
    match kind {
        "decision" => "decisions".into(),
        "constraint" => "constraints".into(),
        "exception" => "exceptions".into(),
        "terminology" | "term" => "terminology".into(),
        "problem" => "problems".into(),
        other if other.ends_with('s') => other.into(),
        other => format!("{other}s"),
    }
}
pub fn singular(dir: &str) -> String {
    match dir {
        "decisions" => "decision".into(),
        "constraints" => "constraint".into(),
        "exceptions" => "exception".into(),
        "terminology" => "terminology".into(),
        "problems" => "problem".into(),
        other => other.trim_end_matches('s').into(),
    }
}

/// Parse YAML text into any deserialisable type (re‑exported so callers do not need serde_yaml).
pub fn parse_yaml<T: serde::de::DeserializeOwned>(text: &str) -> Result<T> {
    Ok(serde_yaml::from_str(text)?)
}

/// Serialise to YAML text.
pub fn to_yaml<T: serde::Serialize>(v: &T) -> Result<String> {
    Ok(serde_yaml::to_string(v)?)
}
